### ISSUE TITLE
wierd interaction due to two `twitch_types` crates used

### ISSUE THREAD

**Issue by Emilgardis** [Emilgardis/twitch_api2#256]
Due to how we currently have `twitch_types` used in `twitch_api2` and `twitch_oauth2`, there's a wierd interaction happening due to the two twitch_api crates used are not the same due to pathing.

To circumvent the issue, users that have specified `twitch_api2` as a path or git dependency will need to do the following:

```toml
[dependencies]
twitch_api2 = { git = ""}

# workaround for https://github.com/Emilgardis/twitch_api2/issues/xxx
[patch.crates-io.twitch_types]
git = "https://github.com/Emilgardis/twitch_api2"
```

this issue manifests as 

`error[E0277]: the trait bound `twitch_types::UserId: From<&twitch_types::basic::UserIdRef>` is not satisfied` on `src/helix/client/client_ext.rs:234:22` and `src/helix/client/client_ext.rs:282:29` rn, which is the only place currently where `twitch_api2` use `twitch_oauth2`s user id

Can this be solved neatly without requiring a patch?

**Comment by Nerixyz** [comment]
For future visitors, after the move from `twitch_api2` to `twitch-rs/twitch_api`:

```toml
[dependencies]
# rev isn't required, but it's good to pin a specific revision
twitch_api = { git = "https://github.com/twitch-rs/twitch_api.git", rev = "340a582" }

# workaround for https://github.com/twitch-rs/twitch_api/issues/256
[patch.crates-io.twitch_types]
git = "https://github.com/twitch-rs/twitch_api.git"
rev = "340a582" # only if you pinned the repo to a specific revision
```

If you don't want to rename every import of `twitch_api2` to `twitch_api`, add the following line in your `main.rs` / `lib.rs`:

```rust
extern crate twitch_api as twitch_api2;
```
